/*
 * Comprehensive Learner Record Service OpenAPI (YAML) Definition
 *
 * The Comprehensive Learner Record Service enables the exchange of data about users and their achievements between a Comprehensive Learner Record Service Provider and the consumers of the associated data. This service has been described using the IMS Model Driven Specification development approach, this being the Platform Specific Model (PSM) of the service.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;

namespace OpenCredentialPublisher.ClrLibrary.Models
{
    public interface IAssertionDType
    {
        AchievementDType Achievement { get; set; }
        Dictionary<string, object> AdditionalProperties { get; set; }
        IList<AssertionClr> AssertionClrs { get; set; }
        int AssertionKey { get; set; }
        string Context { get; set; }
        float? CreditsEarned { get; set; }
        DateTime? EndDate { get; set; }
        List<EndorsementDType> Endorsements { get; set; }
        List<EvidenceDType> Evidence { get; set; }
        string Id { get; set; }
        string Image { get; set; }
        bool IsSigned { get; set; }
        DateTime? IssuedOn { get; set; }
        string LicenseNumber { get; set; }
        string Narrative { get; set; }
        IdentityDType Recipient { get; set; }
        List<ResultDType> Results { get; set; }
        string RevocationReason { get; set; }
        bool? Revoked { get; set; }
        string Role { get; set; }
        List<string> SignedEndorsements { get; set; }
        ProfileDType Source { get; set; }
        DateTime? StartDate { get; set; }
        string Term { get; set; }
        string Type { get; set; }
        VerificationDType Verification { get; set; }

        string ToJson();
    }
}