/*
 * Comprehensive Learner Record Service OpenAPI (YAML) Definition
 *
 * The Comprehensive Learner Record Service enables the exchange of data about users and their achievements between a Comprehensive Learner Record Service Provider and the consumers of the associated data. This service has been described using the IMS Model Driven Specification development approach, this being the Platform Specific Model (PSM) of the service.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: https://openapi-generator.tech
 */

using System.Collections.Generic;

namespace OpenCredentialPublisher.ClrLibrary.Models
{
    public interface ICommonProfileDType
    {
        string AdditionalName { get; set; }
        Dictionary<string, object> AdditionalProperties { get; set; }
        AddressDType Address { get; set; }
        string Description { get; set; }
        string Email { get; set; }
        string FamilyName { get; set; }
        string GivenName { get; set; }
        string Id { get; set; }
        List<SystemIdentifierDType> Identifiers { get; set; }
        string Image { get; set; }
        string Name { get; set; }
        string Official { get; set; }
        CryptographicKeyDType PublicKey { get; set; }
        string RevocationList { get; set; }
        string SourcedId { get; set; }
        string StudentId { get; set; }
        string Telephone { get; set; }
        string Type { get; set; }
        string Url { get; set; }
        VerificationDType Verification { get; set; }

        string ToJson();
    }
}