/*
 * Comprehensive Learner Record Service OpenAPI (YAML) Definition
 *
 * The Comprehensive Learner Record Service enables the exchange of data about users and their achievements between a Comprehensive Learner Record Service Provider and the consumers of the associated data. This service has been described using the IMS Model Driven Specification development approach, this being the Platform Specific Model (PSM) of the service.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: https://openapi-generator.tech
 */

using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OpenCredentialPublisher.ClrLibrary.Models
{ 
    /// <summary>
    /// Describes a rubric criterion level. 
    /// </summary>
    public partial class RubricCriterionLevelDType
    { 
        /// <summary>
        /// Unique IRI for the ResultCriterionLevel. Model Primitive Datatype = NormalizedString.
        /// </summary>
        /// <value>Unique IRI for the ResultCriterionLevel. Model Primitive Datatype = NormalizedString.</value>
        [Required]
        [JsonPropertyName("id"), Newtonsoft.Json.JsonProperty("id")]
        [Description("Unique IRI for the ResultCriterionLevel. Model Primitive Datatype = NormalizedString.")]
        public string Id { get; set; }
        
        /// <summary>
        /// The JSON-LD type of this object. Normally 'RubricCriterionLevel'. Model Primitive Datatype = String.
        /// </summary>
        /// <value>The JSON-LD type of this object. Normally 'RubricCriterionLevel'. Model Primitive Datatype = String.</value>
        [JsonPropertyName("type"), Newtonsoft.Json.JsonProperty("type")]
        [Description("The JSON-LD type of this object. Normally 'RubricCriterionLevel'. Model Primitive Datatype = String.")]
        public string Type { get; set; }
        
        /// <summary>
        /// The alignments between this rubric criterion level and nodes in external frameworks. 
        /// </summary>
        /// <value>The alignments between this rubric criterion level and nodes in external frameworks. </value>
        [JsonPropertyName("alignments"), Newtonsoft.Json.JsonProperty("alignments")]
        [Description("The alignments between this rubric criterion level and nodes in external frameworks. ")]
        public virtual List<AlignmentDType> Alignments { get; set; }
        
        /// <summary>
        /// A description of the rubric criterion level. Model Primitive Datatype = String.
        /// </summary>
        /// <value>A description of the rubric criterion level. Model Primitive Datatype = String.</value>
        [JsonPropertyName("description"), Newtonsoft.Json.JsonProperty("description")]
        [Description("A description of the rubric criterion level. Model Primitive Datatype = String.")]
        public string Description { get; set; }
        
        /// <summary>
        /// The rubric performance level in terms of success. Model Primitive Datatype = String.
        /// </summary>
        /// <value>The rubric performance level in terms of success. Model Primitive Datatype = String.</value>
        [JsonPropertyName("level"), Newtonsoft.Json.JsonProperty("level")]
        [Description("The rubric performance level in terms of success. Model Primitive Datatype = String.")]
        public string Level { get; set; }
        
        /// <summary>
        /// The name of the RubricCriterionLevel. Model Primitive Datatype = String.
        /// </summary>
        /// <value>The name of the RubricCriterionLevel. Model Primitive Datatype = String.</value>
        [Required]
        [JsonPropertyName("name"), Newtonsoft.Json.JsonProperty("name")]
        [Description("The name of the RubricCriterionLevel. Model Primitive Datatype = String.")]
        public string Name { get; set; }
        
        /// <summary>
        /// The number of grade points corresponding to a specific rubric level. Model Primitive Datatype = String.
        /// </summary>
        /// <value>The number of grade points corresponding to a specific rubric level. Model Primitive Datatype = String.</value>
        [JsonPropertyName("points"), Newtonsoft.Json.JsonProperty("points")]
        [Description("The number of grade points corresponding to a specific rubric level. Model Primitive Datatype = String.")]
        public string Points { get; set; }
        
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this, new JsonSerializerOptions { IgnoreNullValues = true });
        }
    }
}
