/*
 * Open Badges OpenAPI (JSON) Definition
 *
 * Open Badges Connect is a secure REST interface for exchanging Open Badges.
 *
 * The version of the OpenAPI document: 2.1
 * Contact: lmattson@imsglobal.org
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;
using OpenCredentialPublisher.ObcLibrary.Converters;

namespace OpenCredentialPublisher.ObcLibrary.Models
{ 
    /// <summary>
    /// Provider configuration information. A provider may support multiple implementations.
    /// </summary>
    public partial class ManifestDType : IEquatable<ManifestDType>
    { 
        /// <summary>
        /// Model Primitive Datatype = NormalizedString. Unique IRI for the manifest.
        /// </summary>
        /// <value>Model Primitive Datatype = NormalizedString. Unique IRI for the manifest.</value>
        [Required]
        [JsonPropertyName("id")]
        [Description("Model Primitive Datatype = NormalizedString. Unique IRI for the manifest.")]
        public string Id { get; set; }
        
        /// <summary>
        /// Model Primitive Datatype = NormalizedString. The JSON-LD type of this object. Normally 'Manifest'.
        /// </summary>
        /// <value>Model Primitive Datatype = NormalizedString. The JSON-LD type of this object. Normally 'Manifest'.</value>
        [JsonPropertyName("type")]
        [Description("Model Primitive Datatype = NormalizedString. The JSON-LD type of this object. Normally 'Manifest'.")]
        public string Type { get; set; } = "Manifest";
        
        /// <summary>
        /// Set of BadgeConnectAPI configurations.
        /// </summary>
        /// <value>Set of BadgeConnectAPI configurations.</value>
        [Required]
        [JsonPropertyName("badgeConnectAPI")]
        [Description("Set of BadgeConnectAPI configurations.")]
        public List<BadgeConnectAPIDType> BadgeConnectAPI { get; set; }
        
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ManifestDType {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  BadgeConnectAPI: ").Append(BadgeConnectAPI).Append("\n");

            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonSerializer.Serialize(this);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ManifestDType)obj);
        }

        /// <summary>
        /// Returns true if ManifestDType instances are equal
        /// </summary>
        /// <param name="other">Instance of ManifestDType to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ManifestDType other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Type == other.Type ||
                    Type != null &&
                    Type.Equals(other.Type)
                ) && 
                (
                    BadgeConnectAPI == other.BadgeConnectAPI ||
                    BadgeConnectAPI != null &&
                    other.BadgeConnectAPI != null &&
                    BadgeConnectAPI.SequenceEqual(other.BadgeConnectAPI)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                                    if (Type != null)
                    hashCode = hashCode * 59 + Type.GetHashCode();
                                    if (BadgeConnectAPI != null)
                    hashCode = hashCode * 59 + BadgeConnectAPI.GetHashCode();
                                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ManifestDType left, ManifestDType right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ManifestDType left, ManifestDType right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
