export module server {
	interface verifyVM {
		clrId: number;
		assertionId: string;
		clrIdentifier: string;
		endorsementId: string;
		verificationDType: {
			verificationKey: number;
			assertionKey?: number;
			assertion: {
				assertionKey: number;
				isSigned: boolean;
				context: string;
				assertionClrs: any[];
				id: string;
				type: string;
				achievement: {
					achievementKey: number;
					achievementClrs: any[];
					id: string;
					type: string;
					achievementType: string;
					alignments: any[];
					associations: any[];
					creditsAvailable?: number;
					description: string;
					endorsements: any[];
					humanCode: string;
					identifiers: any[];
					name: string;
					fieldOfStudy: string;
					image: string;
					issuer: {
						id: string;
						type: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: {
								id: string;
								type: string;
								additionalName: string;
								address: any;
								description: string;
								email: string;
								familyName: string;
								givenName: string;
								identifiers: any[];
								image: string;
								name: string;
								official: string;
								publicKey: {
									cryptographicKeyKey: number;
									context: string;
									id: string;
									type: string;
									owner: string;
									publicKeyPem: string;
									additionalProperties: { [index: string]: any };
								};
								revocationList: string;
								sourcedId: string;
								studentId: string;
								telephone: string;
								url: string;
								verification: any;
								additionalProperties: { [index: string]: any };
								endorsementProfileKey: number;
								profileKey?: number;
								profile: any;
							};
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						additionalName: string;
						birthDate: Date;
						description: string;
						email: string;
						endorsements: any[];
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						parentOrg: any;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						signedEndorsements: string[];
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						profileKey: number;
						endorsementProfile: {
							id: string;
							type: string;
							additionalName: string;
							address: {
								addressKey: number;
								endorsementProfileKey?: number;
								endorsementProfile: any;
								profileKey?: number;
								profile: any;
								id: string;
								type: string;
								addressCountry: string;
								addressLocality: string;
								addressRegion: string;
								postalCode: string;
								postOfficeBoxNumber: string;
								streetAddress: string;
								additionalProperties: { [index: string]: any };
							};
							description: string;
							email: string;
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							endorsementProfileKey: number;
							profileKey?: number;
							profile: any;
						};
					};
					level: string;
					requirement: {
						criteriaKey: number;
						achievementKey?: number;
						achievement: any;
						id: string;
						type: string;
						narrative: string;
						additionalProperties: { [index: string]: any };
					};
					resultDescriptions: any[];
					signedEndorsements: string[];
					specialization: string;
					tags: string[];
					additionalProperties: { [index: string]: any };
				};
				creditsEarned?: number;
				activityEndDate?: Date;
				endorsements: any[];
				evidence: any[];
				expires?: Date;
				image: string;
				issuedOn?: Date;
				licenseNumber: string;
				narrative: string;
				recipient: {
					identityKey: number;
					id: string;
					type: string;
					identity: string;
					hashed: boolean;
					salt: string;
					additionalProperties: { [index: string]: any };
				};
				results: any[];
				revocationReason: string;
				revoked?: boolean;
				role: string;
				signedEndorsements: string[];
				source: {
					id: string;
					type: string;
					address: {
						addressKey: number;
						endorsementProfileKey?: number;
						endorsementProfile: {
							id: string;
							type: string;
							additionalName: string;
							address: any;
							description: string;
							email: string;
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							endorsementProfileKey: number;
							profileKey?: number;
							profile: any;
						};
						profileKey?: number;
						profile: any;
						id: string;
						type: string;
						addressCountry: string;
						addressLocality: string;
						addressRegion: string;
						postalCode: string;
						postOfficeBoxNumber: string;
						streetAddress: string;
						additionalProperties: { [index: string]: any };
					};
					additionalName: string;
					birthDate: Date;
					description: string;
					email: string;
					endorsements: any[];
					familyName: string;
					givenName: string;
					identifiers: any[];
					image: string;
					name: string;
					official: string;
					parentOrg: any;
					publicKey: {
						cryptographicKeyKey: number;
						context: string;
						id: string;
						type: string;
						owner: string;
						publicKeyPem: string;
						additionalProperties: { [index: string]: any };
					};
					revocationList: string;
					signedEndorsements: string[];
					sourcedId: string;
					studentId: string;
					telephone: string;
					url: string;
					verification: any;
					additionalProperties: { [index: string]: any };
					profileKey: number;
					endorsementProfile: {
						id: string;
						type: string;
						additionalName: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: any;
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						description: string;
						email: string;
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						endorsementProfileKey: number;
						profileKey?: number;
						profile: any;
					};
				};
				activityStartDate?: Date;
				term: string;
				verification: any;
				additionalProperties: { [index: string]: any };
			};
			clrKey?: number;
			clr: {
				context: string;
				id: string;
				type: string;
				achievements: any[];
				assertions: any[];
				issuedOn: Date;
				learner: {
					id: string;
					type: string;
					address: {
						addressKey: number;
						endorsementProfileKey?: number;
						endorsementProfile: {
							id: string;
							type: string;
							additionalName: string;
							address: any;
							description: string;
							email: string;
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							endorsementProfileKey: number;
							profileKey?: number;
							profile: any;
						};
						profileKey?: number;
						profile: any;
						id: string;
						type: string;
						addressCountry: string;
						addressLocality: string;
						addressRegion: string;
						postalCode: string;
						postOfficeBoxNumber: string;
						streetAddress: string;
						additionalProperties: { [index: string]: any };
					};
					additionalName: string;
					birthDate: Date;
					description: string;
					email: string;
					endorsements: any[];
					familyName: string;
					givenName: string;
					identifiers: any[];
					image: string;
					name: string;
					official: string;
					parentOrg: any;
					publicKey: {
						cryptographicKeyKey: number;
						context: string;
						id: string;
						type: string;
						owner: string;
						publicKeyPem: string;
						additionalProperties: { [index: string]: any };
					};
					revocationList: string;
					signedEndorsements: string[];
					sourcedId: string;
					studentId: string;
					telephone: string;
					url: string;
					verification: any;
					additionalProperties: { [index: string]: any };
					profileKey: number;
					endorsementProfile: {
						id: string;
						type: string;
						additionalName: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: any;
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						description: string;
						email: string;
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						endorsementProfileKey: number;
						profileKey?: number;
						profile: any;
					};
				};
				name: string;
				partial?: boolean;
				publisher: {
					id: string;
					type: string;
					address: {
						addressKey: number;
						endorsementProfileKey?: number;
						endorsementProfile: {
							id: string;
							type: string;
							additionalName: string;
							address: any;
							description: string;
							email: string;
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							endorsementProfileKey: number;
							profileKey?: number;
							profile: any;
						};
						profileKey?: number;
						profile: any;
						id: string;
						type: string;
						addressCountry: string;
						addressLocality: string;
						addressRegion: string;
						postalCode: string;
						postOfficeBoxNumber: string;
						streetAddress: string;
						additionalProperties: { [index: string]: any };
					};
					additionalName: string;
					birthDate: Date;
					description: string;
					email: string;
					endorsements: any[];
					familyName: string;
					givenName: string;
					identifiers: any[];
					image: string;
					name: string;
					official: string;
					parentOrg: any;
					publicKey: {
						cryptographicKeyKey: number;
						context: string;
						id: string;
						type: string;
						owner: string;
						publicKeyPem: string;
						additionalProperties: { [index: string]: any };
					};
					revocationList: string;
					signedEndorsements: string[];
					sourcedId: string;
					studentId: string;
					telephone: string;
					url: string;
					verification: any;
					additionalProperties: { [index: string]: any };
					profileKey: number;
					endorsementProfile: {
						id: string;
						type: string;
						additionalName: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: any;
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						description: string;
						email: string;
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						endorsementProfileKey: number;
						profileKey?: number;
						profile: any;
					};
				};
				revocationReason: string;
				revoked?: boolean;
				signedAssertions: string[];
				signedEndorsements: string[];
				verification: any;
				additionalProperties: { [index: string]: any };
				clrKey: number;
				achievementClrs: any[];
				assertionClrs: any[];
			};
			endorsementKey?: number;
			endorsement: {
				endorsementKey: number;
				context: string;
				achievementKey?: number;
				achievement: {
					achievementKey: number;
					achievementClrs: any[];
					id: string;
					type: string;
					achievementType: string;
					alignments: any[];
					associations: any[];
					creditsAvailable?: number;
					description: string;
					endorsements: any[];
					humanCode: string;
					identifiers: any[];
					name: string;
					fieldOfStudy: string;
					image: string;
					issuer: {
						id: string;
						type: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: {
								id: string;
								type: string;
								additionalName: string;
								address: any;
								description: string;
								email: string;
								familyName: string;
								givenName: string;
								identifiers: any[];
								image: string;
								name: string;
								official: string;
								publicKey: {
									cryptographicKeyKey: number;
									context: string;
									id: string;
									type: string;
									owner: string;
									publicKeyPem: string;
									additionalProperties: { [index: string]: any };
								};
								revocationList: string;
								sourcedId: string;
								studentId: string;
								telephone: string;
								url: string;
								verification: any;
								additionalProperties: { [index: string]: any };
								endorsementProfileKey: number;
								profileKey?: number;
								profile: any;
							};
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						additionalName: string;
						birthDate: Date;
						description: string;
						email: string;
						endorsements: any[];
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						parentOrg: any;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						signedEndorsements: string[];
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						profileKey: number;
						endorsementProfile: {
							id: string;
							type: string;
							additionalName: string;
							address: {
								addressKey: number;
								endorsementProfileKey?: number;
								endorsementProfile: any;
								profileKey?: number;
								profile: any;
								id: string;
								type: string;
								addressCountry: string;
								addressLocality: string;
								addressRegion: string;
								postalCode: string;
								postOfficeBoxNumber: string;
								streetAddress: string;
								additionalProperties: { [index: string]: any };
							};
							description: string;
							email: string;
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							endorsementProfileKey: number;
							profileKey?: number;
							profile: any;
						};
					};
					level: string;
					requirement: {
						criteriaKey: number;
						achievementKey?: number;
						achievement: any;
						id: string;
						type: string;
						narrative: string;
						additionalProperties: { [index: string]: any };
					};
					resultDescriptions: any[];
					signedEndorsements: string[];
					specialization: string;
					tags: string[];
					additionalProperties: { [index: string]: any };
				};
				assertionKey?: number;
				assertion: {
					assertionKey: number;
					isSigned: boolean;
					context: string;
					assertionClrs: any[];
					id: string;
					type: string;
					achievement: {
						achievementKey: number;
						achievementClrs: any[];
						id: string;
						type: string;
						achievementType: string;
						alignments: any[];
						associations: any[];
						creditsAvailable?: number;
						description: string;
						endorsements: any[];
						humanCode: string;
						identifiers: any[];
						name: string;
						fieldOfStudy: string;
						image: string;
						issuer: {
							id: string;
							type: string;
							address: {
								addressKey: number;
								endorsementProfileKey?: number;
								endorsementProfile: {
									id: string;
									type: string;
									additionalName: string;
									address: any;
									description: string;
									email: string;
									familyName: string;
									givenName: string;
									identifiers: any[];
									image: string;
									name: string;
									official: string;
									publicKey: {
										cryptographicKeyKey: number;
										context: string;
										id: string;
										type: string;
										owner: string;
										publicKeyPem: string;
										additionalProperties: { [index: string]: any };
									};
									revocationList: string;
									sourcedId: string;
									studentId: string;
									telephone: string;
									url: string;
									verification: any;
									additionalProperties: { [index: string]: any };
									endorsementProfileKey: number;
									profileKey?: number;
									profile: any;
								};
								profileKey?: number;
								profile: any;
								id: string;
								type: string;
								addressCountry: string;
								addressLocality: string;
								addressRegion: string;
								postalCode: string;
								postOfficeBoxNumber: string;
								streetAddress: string;
								additionalProperties: { [index: string]: any };
							};
							additionalName: string;
							birthDate: Date;
							description: string;
							email: string;
							endorsements: any[];
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							parentOrg: any;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							signedEndorsements: string[];
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							profileKey: number;
							endorsementProfile: {
								id: string;
								type: string;
								additionalName: string;
								address: {
									addressKey: number;
									endorsementProfileKey?: number;
									endorsementProfile: any;
									profileKey?: number;
									profile: any;
									id: string;
									type: string;
									addressCountry: string;
									addressLocality: string;
									addressRegion: string;
									postalCode: string;
									postOfficeBoxNumber: string;
									streetAddress: string;
									additionalProperties: { [index: string]: any };
								};
								description: string;
								email: string;
								familyName: string;
								givenName: string;
								identifiers: any[];
								image: string;
								name: string;
								official: string;
								publicKey: {
									cryptographicKeyKey: number;
									context: string;
									id: string;
									type: string;
									owner: string;
									publicKeyPem: string;
									additionalProperties: { [index: string]: any };
								};
								revocationList: string;
								sourcedId: string;
								studentId: string;
								telephone: string;
								url: string;
								verification: any;
								additionalProperties: { [index: string]: any };
								endorsementProfileKey: number;
								profileKey?: number;
								profile: any;
							};
						};
						level: string;
						requirement: {
							criteriaKey: number;
							achievementKey?: number;
							achievement: any;
							id: string;
							type: string;
							narrative: string;
							additionalProperties: { [index: string]: any };
						};
						resultDescriptions: any[];
						signedEndorsements: string[];
						specialization: string;
						tags: string[];
						additionalProperties: { [index: string]: any };
					};
					creditsEarned?: number;
					activityEndDate?: Date;
					endorsements: any[];
					evidence: any[];
					expires?: Date;
					image: string;
					issuedOn?: Date;
					licenseNumber: string;
					narrative: string;
					recipient: {
						identityKey: number;
						id: string;
						type: string;
						identity: string;
						hashed: boolean;
						salt: string;
						additionalProperties: { [index: string]: any };
					};
					results: any[];
					revocationReason: string;
					revoked?: boolean;
					role: string;
					signedEndorsements: string[];
					source: {
						id: string;
						type: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: {
								id: string;
								type: string;
								additionalName: string;
								address: any;
								description: string;
								email: string;
								familyName: string;
								givenName: string;
								identifiers: any[];
								image: string;
								name: string;
								official: string;
								publicKey: {
									cryptographicKeyKey: number;
									context: string;
									id: string;
									type: string;
									owner: string;
									publicKeyPem: string;
									additionalProperties: { [index: string]: any };
								};
								revocationList: string;
								sourcedId: string;
								studentId: string;
								telephone: string;
								url: string;
								verification: any;
								additionalProperties: { [index: string]: any };
								endorsementProfileKey: number;
								profileKey?: number;
								profile: any;
							};
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						additionalName: string;
						birthDate: Date;
						description: string;
						email: string;
						endorsements: any[];
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						parentOrg: any;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						signedEndorsements: string[];
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						profileKey: number;
						endorsementProfile: {
							id: string;
							type: string;
							additionalName: string;
							address: {
								addressKey: number;
								endorsementProfileKey?: number;
								endorsementProfile: any;
								profileKey?: number;
								profile: any;
								id: string;
								type: string;
								addressCountry: string;
								addressLocality: string;
								addressRegion: string;
								postalCode: string;
								postOfficeBoxNumber: string;
								streetAddress: string;
								additionalProperties: { [index: string]: any };
							};
							description: string;
							email: string;
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							endorsementProfileKey: number;
							profileKey?: number;
							profile: any;
						};
					};
					activityStartDate?: Date;
					term: string;
					verification: any;
					additionalProperties: { [index: string]: any };
				};
				profileKey?: number;
				profile: {
					id: string;
					type: string;
					address: {
						addressKey: number;
						endorsementProfileKey?: number;
						endorsementProfile: {
							id: string;
							type: string;
							additionalName: string;
							address: any;
							description: string;
							email: string;
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							endorsementProfileKey: number;
							profileKey?: number;
							profile: any;
						};
						profileKey?: number;
						profile: any;
						id: string;
						type: string;
						addressCountry: string;
						addressLocality: string;
						addressRegion: string;
						postalCode: string;
						postOfficeBoxNumber: string;
						streetAddress: string;
						additionalProperties: { [index: string]: any };
					};
					additionalName: string;
					birthDate: Date;
					description: string;
					email: string;
					endorsements: any[];
					familyName: string;
					givenName: string;
					identifiers: any[];
					image: string;
					name: string;
					official: string;
					parentOrg: any;
					publicKey: {
						cryptographicKeyKey: number;
						context: string;
						id: string;
						type: string;
						owner: string;
						publicKeyPem: string;
						additionalProperties: { [index: string]: any };
					};
					revocationList: string;
					signedEndorsements: string[];
					sourcedId: string;
					studentId: string;
					telephone: string;
					url: string;
					verification: any;
					additionalProperties: { [index: string]: any };
					profileKey: number;
					endorsementProfile: {
						id: string;
						type: string;
						additionalName: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: any;
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						description: string;
						email: string;
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						endorsementProfileKey: number;
						profileKey?: number;
						profile: any;
					};
				};
				id: string;
				type: string;
				claim: {
					id: string;
					type: string;
					endorsementComment: string;
					additionalProperties: { [index: string]: any };
					endorsementClaimKey: number;
					endorsementKey: number;
					endorsement: any;
				};
				issuedOn: Date;
				issuer: {
					id: string;
					type: string;
					additionalName: string;
					address: {
						addressKey: number;
						endorsementProfileKey?: number;
						endorsementProfile: any;
						profileKey?: number;
						profile: {
							id: string;
							type: string;
							address: any;
							additionalName: string;
							birthDate: Date;
							description: string;
							email: string;
							endorsements: any[];
							familyName: string;
							givenName: string;
							identifiers: any[];
							image: string;
							name: string;
							official: string;
							parentOrg: any;
							publicKey: {
								cryptographicKeyKey: number;
								context: string;
								id: string;
								type: string;
								owner: string;
								publicKeyPem: string;
								additionalProperties: { [index: string]: any };
							};
							revocationList: string;
							signedEndorsements: string[];
							sourcedId: string;
							studentId: string;
							telephone: string;
							url: string;
							verification: any;
							additionalProperties: { [index: string]: any };
							profileKey: number;
							endorsementProfile: any;
						};
						id: string;
						type: string;
						addressCountry: string;
						addressLocality: string;
						addressRegion: string;
						postalCode: string;
						postOfficeBoxNumber: string;
						streetAddress: string;
						additionalProperties: { [index: string]: any };
					};
					description: string;
					email: string;
					familyName: string;
					givenName: string;
					identifiers: any[];
					image: string;
					name: string;
					official: string;
					publicKey: {
						cryptographicKeyKey: number;
						context: string;
						id: string;
						type: string;
						owner: string;
						publicKeyPem: string;
						additionalProperties: { [index: string]: any };
					};
					revocationList: string;
					sourcedId: string;
					studentId: string;
					telephone: string;
					url: string;
					verification: any;
					additionalProperties: { [index: string]: any };
					endorsementProfileKey: number;
					profileKey?: number;
					profile: {
						id: string;
						type: string;
						address: {
							addressKey: number;
							endorsementProfileKey?: number;
							endorsementProfile: any;
							profileKey?: number;
							profile: any;
							id: string;
							type: string;
							addressCountry: string;
							addressLocality: string;
							addressRegion: string;
							postalCode: string;
							postOfficeBoxNumber: string;
							streetAddress: string;
							additionalProperties: { [index: string]: any };
						};
						additionalName: string;
						birthDate: Date;
						description: string;
						email: string;
						endorsements: any[];
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						parentOrg: any;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						signedEndorsements: string[];
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						profileKey: number;
						endorsementProfile: any;
					};
				};
				revocationReason: string;
				revoked?: boolean;
				verification: any;
				additionalProperties: { [index: string]: any };
			};
			profileKey?: number;
			profile: {
				id: string;
				type: string;
				address: {
					addressKey: number;
					endorsementProfileKey?: number;
					endorsementProfile: {
						id: string;
						type: string;
						additionalName: string;
						address: any;
						description: string;
						email: string;
						familyName: string;
						givenName: string;
						identifiers: any[];
						image: string;
						name: string;
						official: string;
						publicKey: {
							cryptographicKeyKey: number;
							context: string;
							id: string;
							type: string;
							owner: string;
							publicKeyPem: string;
							additionalProperties: { [index: string]: any };
						};
						revocationList: string;
						sourcedId: string;
						studentId: string;
						telephone: string;
						url: string;
						verification: any;
						additionalProperties: { [index: string]: any };
						endorsementProfileKey: number;
						profileKey?: number;
						profile: any;
					};
					profileKey?: number;
					profile: any;
					id: string;
					type: string;
					addressCountry: string;
					addressLocality: string;
					addressRegion: string;
					postalCode: string;
					postOfficeBoxNumber: string;
					streetAddress: string;
					additionalProperties: { [index: string]: any };
				};
				additionalName: string;
				birthDate: Date;
				description: string;
				email: string;
				endorsements: any[];
				familyName: string;
				givenName: string;
				identifiers: any[];
				image: string;
				name: string;
				official: string;
				parentOrg: any;
				publicKey: {
					cryptographicKeyKey: number;
					context: string;
					id: string;
					type: string;
					owner: string;
					publicKeyPem: string;
					additionalProperties: { [index: string]: any };
				};
				revocationList: string;
				signedEndorsements: string[];
				sourcedId: string;
				studentId: string;
				telephone: string;
				url: string;
				verification: any;
				additionalProperties: { [index: string]: any };
				profileKey: number;
				endorsementProfile: {
					id: string;
					type: string;
					additionalName: string;
					address: {
						addressKey: number;
						endorsementProfileKey?: number;
						endorsementProfile: any;
						profileKey?: number;
						profile: any;
						id: string;
						type: string;
						addressCountry: string;
						addressLocality: string;
						addressRegion: string;
						postalCode: string;
						postOfficeBoxNumber: string;
						streetAddress: string;
						additionalProperties: { [index: string]: any };
					};
					description: string;
					email: string;
					familyName: string;
					givenName: string;
					identifiers: any[];
					image: string;
					name: string;
					official: string;
					publicKey: {
						cryptographicKeyKey: number;
						context: string;
						id: string;
						type: string;
						owner: string;
						publicKeyPem: string;
						additionalProperties: { [index: string]: any };
					};
					revocationList: string;
					sourcedId: string;
					studentId: string;
					telephone: string;
					url: string;
					verification: any;
					additionalProperties: { [index: string]: any };
					endorsementProfileKey: number;
					profileKey?: number;
					profile: any;
				};
			};
			id: string;
			type: any;
			allowedOrigins: string[];
			creator: string;
			startsWith: string[];
			verificationProperty: string;
			additionalProperties: { [index: string]: any };
		};
	}
}
